//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonusCards
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ErrorImage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int NoCardImage = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int NoCardImageBack = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int NoCardImageBackB = 2130837508;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int btnAddImage = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int btnApply = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int btnCancel = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int btnEnlargeImage = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int btnMoveLeft = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int btnMoveRight = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int btnRemoveImage = 2131034120;
			
			// aapt resource value: 0x7f050019
			public const int cardImageView = 2131034137;
			
			// aapt resource value: 0x7f050003
			public const int etCardName = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int etShopName = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int ivCardThumbnail = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int ivNoImage = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout2 = 2131034131;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout5 = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout6 = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int linearLayoutImagesBox = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int llCardImages = 2131034126;
			
			// aapt resource value: 0x7f050018
			public const int lvCards = 2131034136;
			
			// aapt resource value: 0x7f05000f
			public const int rlNoImage = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int scrollView1 = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int tvCardName = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int tvDistance = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int tvLocation = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int tvLocationA = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int tvShopName = 2131034132;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddCard = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CardItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewCard = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int AddCard = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int Exit = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int MainEditCard = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int addcard_Apply = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int addcard_Cancel = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int addcard_ShopName = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int addcard_addimage = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int addcard_cardName = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int addcard_enlargeimage = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int addcard_moveLeft = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int addcard_moveRight = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int addcard_removeimage = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int addcard_shopName = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int distance_Here = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int distance_KM = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int distance_M = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int distance_Unknown = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int error_LocationUnavailable = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int viewcard_Edit = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int viewcard_Left = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int viewcard_Right = 2130968598;
			
			private String()
			{
			}
		}
	}
}
